name: Compilación y pruebas C#
on: push
jobs:
  Compilacion:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compilamos
        run: donet build
      - name: Ejecutamos las pruebas
        run: donet test
